services:
  - docker

before_install:
  - git clone https://github.com/ffmpegwasm/FFmpeg.git
  - git submodule init
  - git submodule update --recursive
  
script:
  - cd FFmpeg
  - git submodule init
  - git submodule update --recursive
  - bash build-with-docker.sh
