dist: bionic

services:
  - docker

before_install:
  - git clone --branch=n4.1.4-js https://github.com/ffmpegwasm/FFmpeg.git
  - /bin/cp -f build-js.sh FFmpeg/
  - chmod +x FFmpeg/build-js.sh
  
script:
  - cd FFmpeg
  - git submodule init
  - git submodule update --recursive
  - bash build-with-docker.sh
  
after_script:
  - cd FFmpeg
  - wget http://gosspublic.alicdn.com/ossutil/1.6.14/ossutil64                           
  - chmod 755 ossutil64
