dist: bionic

services:
  - docker

before_install:
  - git clone https://github.com/ffmpegwasm/FFmpeg.git
  - /bin/cp -f build-js.sh FFmpeg/
  - chmod +x FFmpeg/build-js.sh
  
script:
  - cd FFmpeg
  - git submodule init
  - git submodule update --recursive
  - bash build-with-docker.sh
  
addons:
  artifacts:
    paths:
      - FFmpeg/build
